'use strict';
const $ = s => document.querySelector(s);
const labels={discovered:'Discovered',reviewed:'Reviewed',shortlisted:'Shortlisted',draft:'Draft',ready:'Ready',applying:'Unconfirmed',needs_input:'Needs input',submitted:'Submitted',interview:'Interview',offer:'Offer',rejected:'Rejected',withdrawn:'Withdrawn',expired:'Expired',skipped:'Skipped',archived:'Archived'};
const colors=['#2459f5','#7198ff','#27a794','#9173dc','#e9a64c'];
const state={data:null,query:'',category:'',status:'',quick:'all',day:'',sort:'recent',view:'list',page:1,stage:'',cohort:'all',learnCategory:'',listCohort:'all'};
const pageSize=15;
const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dayKey = d => new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
const fmt = (d, options={month:'short',day:'numeric',year:'numeric'}) => d ? new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',...options}).format(new Date(d)) : 'Not submitted';
const todayKey=()=>dayKey(new Date());
const badge = status => `<span class="status-badge status-${esc(status)}">${esc(labels[status]||status)}</span>`;
const colorFor = text => colors[[...text].reduce((a,c)=>a+c.charCodeAt(0),0)%colors.length];
const initials = text => text.split(/\s+/).slice(0,2).map(s=>s[0]).join('').toUpperCase();
let focusedBeforeDialog;
function summaries(){
 const rows=state.data.applications, submitted=rows.filter(r=>r.submittedAt), today=submitted.filter(r=>r.submittedDay===todayKey());
 $('#total').textContent=submitted.length; $('#companies').textContent=`Across ${new Set(submitted.map(r=>r.company.toLowerCase())).size} companies`;
 $('#interviews').textContent=rows.filter(r=>['interview','offer'].includes(r.status)).length;
 $('#attention').textContent=rows.filter(r=>['needs_input','applying'].includes(r.status)).length;
 $('#today').textContent=today.length; const goal=state.data.dailyGoal;
 $('#goal-ring').style.setProperty('--progress',`${Math.min(100,today.length/goal*100)}%`);
 $('#goal-percent').textContent=`${Math.round(today.length/goal*100)}%`;
 $('#goal-caption').textContent=today.length>=goal?'Goal complete. Nicely done.':`${Math.max(0,goal-today.length)} more to today’s goal`;
 $('#nav-count').textContent=rows.length;
 $('#current-date').textContent=fmt(new Date(),{weekday:'short',month:'short',day:'numeric',year:'numeric'});
 const days=Array.from({length:14},(_,i)=>{let date=new Date(`${todayKey()}T12:00:00-04:00`);date.setUTCDate(date.getUTCDate()-13+i);const key=dayKey(date);return {key,date,count:submitted.filter(r=>r.submittedDay===key).length}});
 const max=Math.max(1,...days.map(d=>d.count));
 $('#chart').innerHTML=days.map((d,i)=>`<button class="chart-day" data-day="${d.key}" aria-label="${fmt(d.date)}: ${d.count} submissions. Filter applications." title="${fmt(d.date)} · ${d.count} submissions"><span class="number">${d.count||''}</span><span class="bar" style="height:${Math.max(2,d.count/max*108)}px;animation-delay:${i*25}ms"></span><span class="day">${fmt(d.date,{day:'numeric'})}</span></button>`).join('');
 $('#chart-total').textContent=`${days.reduce((a,d)=>a+d.count,0)} submissions in 14 days`;
 const categories=[...new Set(rows.map(r=>r.category))].sort();
 const catValues=categories.map(c=>({name:c,count:submitted.filter(r=>r.category===c).length})).sort((a,b)=>b.count-a.count);
 $('#categories').innerHTML=catValues.map((c,i)=>`<button class="category-row" data-category="${esc(c.name)}" aria-label="Filter ${esc(c.name)}"><span class="category-meta"><span>${esc(c.name)}</span><span>${c.count} <span aria-hidden="true">·</span> ${submitted.length?Math.round(c.count/submitted.length*100):0}%</span></span><span class="category-track"><i style="--color:${colors[i]};width:${submitted.length?c.count/submitted.length*100:0}%"></i></span></button>`).join('');
 $('#category').innerHTML='<option value="">All disciplines</option>'+categories.map(c=>`<option>${esc(c)}</option>`).join('');$('#category').value=state.category;
 $('#status').innerHTML='<option value="">All statuses</option>'+Object.keys(labels).filter(s=>rows.some(r=>r.status===s)).map(s=>`<option value="${s}">${labels[s]}</option>`).join('');$('#status').value=state.status;
 renderPipeline();renderLearning();
 $('#sync').textContent=`Updated ${fmt(state.data.updatedAt,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}`;
}
function filtered(){
 return state.data.applications.filter(r=>{
  if(state.query&&!`${r.company} ${r.title} ${r.location}`.toLowerCase().includes(state.query.toLowerCase()))return false;
  if(state.category&&r.category!==state.category)return false;
  if(state.stage&&stageOf(r)!==state.stage)return false;
  if(state.status&&r.status!==state.status)return false;
  if(state.day&&r.submittedDay!==state.day)return false;
  if(state.listCohort!=='all'&&!inCohort(r,state.listCohort))return false;
  if(state.quick==='submitted'&&!r.submittedAt)return false;
  if(state.quick==='attention'&&!['applying','needs_input'].includes(r.status))return false;
  if(state.quick==='today'&&r.submittedDay!==todayKey())return false;
  return true;
 }).sort((a,b)=>state.sort==='company'?a.company.localeCompare(b.company)||a.title.localeCompare(b.title):String(state.sort==='submitted'?b.submittedAt||'':b.updatedAt).localeCompare(String(state.sort==='submitted'?a.submittedAt||'':a.updatedAt))||b.id-a.id);
}
function render(){
 if(!state.data)return;
 const all=filtered();const pages=Math.max(1,Math.ceil(all.length/pageSize));state.page=Math.min(state.page,pages);const rows=all.slice((state.page-1)*pageSize,state.page*pageSize);
 $('#result-total').textContent=state.data.applications.length;$('#showing').textContent=`${all.length} results${state.day?' · '+state.day:''}${state.listCohort!=='all'?' · submitted in last '+state.listCohort+' days':''}`;
 $('#page-info').textContent=all.length?`${(state.page-1)*pageSize+1}–${Math.min(state.page*pageSize,all.length)} of ${all.length} roles`:'0 roles';$('#prev').disabled=state.page===1;$('#next').disabled=state.page===pages;
 document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===state.quick)));
 $('#list-view').setAttribute('aria-pressed',String(state.view==='list'));$('#timeline-view').setAttribute('aria-pressed',String(state.view==='timeline'));
 if(!all.length){$('#results').innerHTML='<div class="empty"><strong>No matching applications.</strong><p>Try another search or reset the filters.</p></div>';return;}
 if(state.view==='timeline'){
  const groups={};rows.forEach(r=>{const key=dayKey(new Date(r.submittedAt||r.updatedAt));(groups[key]??=[]).push(r)});
  $('#results').innerHTML='<div class="timeline">'+Object.entries(groups).map(([day,items])=>`<section class="timeline-group"><h3>${fmt(day+'T12:00:00-04:00')} <span class="count-pill">${items.length}</span></h3>${items.map(r=>`<article class="timeline-item"><div><button data-detail="${r.id}"><strong>${esc(r.company)} <span aria-hidden="true">↗</span></strong><p>${esc(r.title)}</p></button><time>${r.submittedAt?'Submitted':'Last activity'} · ${fmt(r.submittedAt||r.updatedAt,{hour:'numeric',minute:'2-digit'})}</time></div><div>${stageBadge(r)}<small class="stage-note">${esc(roundLabel(r))}</small></div></article>`).join('')}</section>`).join('')+'</div>';
 }else{
  $('#results').innerHTML=`<div class="table-wrap"><table><thead><tr><th scope="col">Company</th><th scope="col">Role / location</th><th scope="col">Discipline</th><th scope="col">Status</th><th scope="col">Submitted</th><th scope="col"><span class="sr-only">Details</span></th></tr></thead><tbody>${rows.map(r=>`<tr><td><div class="company-cell"><span class="company-logo" style="--color:${colorFor(r.company)}">${esc(initials(r.company))}</span><strong>${esc(r.company)}</strong></div></td><td><button class="role-button" data-detail="${r.id}">${esc(r.title)}</button><span class="role-location">${esc(r.location)}</span></td><td><span class="category-tag">${esc(r.category)}</span></td><td>${stageBadge(r)}<small class="stage-note">${esc(roundLabel(r))}</small></td><td class="date-cell">${r.submittedAt?fmt(r.submittedAt,{month:'short',day:'numeric',year:'numeric'}):'—'}</td><td><button class="detail-link" data-detail="${r.id}" aria-label="View ${esc(r.company)} ${esc(r.title)} details">↗</button></td></tr>`).join('')}</tbody></table></div>`;
 }
}
function detail(id){
 const r=state.data.applications.find(r=>r.id===Number(id));if(!r)return;
 focusedBeforeDialog=document.activeElement;
 $('#detail-body').innerHTML=`<span class="company-logo" style="--color:${colorFor(r.company)}">${esc(initials(r.company))}</span><div class="detail-company">${esc(r.company)}</div><h2>${esc(r.title)}</h2>${stageBadge(r)}<div class="detail-meta"><span>${esc(r.category)}</span><span>·</span><span>${esc(r.location)}</span></div>${r.url?`<a class="job-url" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">View original posting ↗</a>`:''}${detailInsights(r)}<section class="history"><h3>Application timeline</h3><div class="history-row"><span>Added to tracker</span><time>${fmt(r.addedAt)}</time></div>${r.history.map(e=>`<div class="history-row"><span>${esc(labels[e.status]||e.status)}</span><time>${fmt(e.at,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}</time></div>`).join('')}${(r.milestones||[]).map(e=>`<div class="history-row"><span>${esc(roundLabel({progress:e.progress})||stageNames[e.progress.stage])}</span><time>${fmt(e.at,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}</time></div>`).join('')}${!r.history.length?'<p>No status changes recorded yet.</p>':''}</section><p class="role-location">Timeline status dates are when recorded in the tracker. Employer decision dates, when available, appear above.</p><p class="role-location">Tracker #${r.id} · Last activity ${fmt(r.updatedAt)}</p>`;
 $('#detail').showModal();
}
function change(){state.page=1;render()}
$('#search').addEventListener('input',e=>{state.query=e.target.value;change()});
$('#category').addEventListener('change',e=>{state.category=e.target.value;change()});
$('#status').addEventListener('change',e=>{state.status=e.target.value;change()});
$('#sort').addEventListener('change',e=>{state.sort=e.target.value;change()});
$('#clear').addEventListener('click',()=>{Object.assign(state,{query:'',category:'',status:'',stage:'',listCohort:'all',day:'',quick:'all',sort:'recent'});$('#search').value='';$('#category').value='';$('#status').value='';$('#sort').value='recent';$('#stage-filter').value='';change()});
$('#prev').addEventListener('click',()=>{state.page--;render()});$('#next').addEventListener('click',()=>{state.page++;render()});
$('#list-view').addEventListener('click',()=>{state.view='list';render()});$('#timeline-view').addEventListener('click',()=>{state.view='timeline';state.sort='submitted';$('#sort').value='submitted';change()});
document.addEventListener('click',e=>{let b=e.target.closest('[data-filter]');if(b){state.quick=b.dataset.filter;state.listCohort='all';state.stage='';$('#stage-filter').value='';state.day='';state.status='';$('#status').value='';change()}b=e.target.closest('[data-detail]');if(b)detail(b.dataset.detail);b=e.target.closest('[data-category]');if(b){state.category=b.dataset.category;$('#category').value=state.category;change();$('#applications').scrollIntoView({behavior:'smooth'})}b=e.target.closest('[data-day]');if(b){state.day=b.dataset.day;state.quick='all';change();$('#applications').scrollIntoView({behavior:'smooth'})}});
$('#detail .close').addEventListener('click',()=>$('#detail').close());$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});$('#detail').addEventListener('close',()=>focusedBeforeDialog?.focus());
let fetching=false;
async function load(){
 if(fetching)return;fetching=true;$('#refresh').disabled=true;
 try{const response=await fetch(`applications.json?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw Error('Data unavailable');const data=await response.json();if(data.version!==1||!Array.isArray(data.applications))throw Error('Invalid data');const changed=!state.data||data.updatedAt!==state.data.updatedAt;state.data=data;if(changed){summaries();render()}$('#error').hidden=true;}
 catch(error){$('#error').textContent=state.data?'Could not refresh. Showing the last loaded snapshot. Try Refresh again.':'The application tracker could not load. Please try Refresh again.';$('#error').hidden=false;
 $('#sync').textContent='Refresh needed';}
 finally{fetching=false;$('#refresh').disabled=false}
}
$('#refresh').addEventListener('click',load);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});setInterval(()=>{if(!document.hidden)load()},60000);load();

const stageNames={awaiting_review:'Awaiting review',input_needed:'Needs input',screening:'Screening task',interview:'Interview',offer:'Offer',rejected:'Rejected',unconfirmed:'Unconfirmed',preparing:'Preparing',withdrawn:'Withdrawn',closed:'Closed'};
const actionNames={wait:'Wait for employer review',complete_application:'Resolve missing application information',complete_screen:'Complete the requested screener',book_interview:'Book the introductory conversation',prepare_interview:'Prepare for the scheduled interview',await_result:'Wait for interview feedback',review_feedback:'Review feedback and refine the next application',review_offer:'Review offer details',verify_receipt:'Check for a receipt before retrying',review_role:'Review role fit and requirements',none:'No current action'};
const feedbackNames={closer_match:'Other candidates were a closer match',general_fit:'General fit decision; specifics not provided',other_candidate:'Another candidate selected',organization_fit:'Small-team / organizational fit decision',unspecified:'No specific reason provided',specific_feedback:'Specific feedback received; review private evidence'};
function stageOf(r){return r.progress?.stage||({submitted:'awaiting_review',needs_input:'input_needed',applying:'unconfirmed',interview:'interview',rejected:'rejected',offer:'offer',withdrawn:'withdrawn',expired:'closed',skipped:'closed',archived:'closed'}[r.status]||'preparing')}
function stageBadge(r){const s=stageOf(r);return `<span class="status-badge stage-${s}">${stageNames[s]||s}</span>`}
function roundLabel(r){const p=r.progress||{};if(stageOf(r)!=='interview')return stageOf(r)==='screening'?'Assessment pending':'';return `${p.round?'Round '+p.round:'Round not specified'} · ${({intro:'Intro',recruiter:'Recruiter',technical:'Technical',research:'Research',hiring_manager:'Hiring manager',onsite:'Onsite',final:'Final'})[p.roundType]||'Type not specified'} · ${({invited:'Invitation received',scheduled:'Scheduled',completed:'Completed',awaiting_result:'Awaiting result'})[p.roundState]||'Status not specified'}`}
function focusStage(stage,category='',listCohort='all'){Object.assign(state,{stage,category,listCohort,quick:'all',status:'',query:'',day:'',page:1});$('#stage-filter').value=stage;$('#category').value=category;$('#status').value='';$('#search').value='';render();$('#applications').scrollIntoView({behavior:'smooth'})}
function renderPipeline(){
 const rows=state.data.applications;
 const stages=['awaiting_review','input_needed','screening','interview','rejected','offer'];
 const captions={awaiting_review:'Submitted · waiting for a decision',input_needed:'Information needed to continue',screening:'Employer task waiting on you',interview:'Invited, scheduled or in progress',rejected:'Closed by the employer',offer:'Offer received'};
 $('#pipeline').innerHTML=stages.map(s=>`<button class="pipeline-card stage-${s}" data-stage="${s}"><span>${stageNames[s]}</span><strong>${rows.filter(r=>stageOf(r)===s).length}</strong><small>${captions[s]}</small><span class="pipeline-arrow" aria-hidden="true">↗</span></button>`).join('');
 $('#pipeline-count').textContent=`${rows.filter(r=>r.submittedAt).length} submissions in total`;
 const active=rows.filter(r=>['screening','interview','offer'].includes(stageOf(r))).sort((a,b)=>(a.progress?.nextAt||'9999').localeCompare(b.progress?.nextAt||'9999'));
 $('#action-list').innerHTML=active.length?active.map(r=>`<button class="action-item" data-detail="${r.id}"><div><strong>${esc(r.company)}</strong>${stageBadge(r)}<p>${esc(r.title)}</p><small>${esc(roundLabel(r))}</small></div><div class="action-task">${esc(actionNames[r.progress?.nextAction]||'Review the next step')}<time>${r.progress?.nextAt?fmt(r.progress.nextAt,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' ET':'No date recorded'}</time><span aria-hidden="true">→</span></div></button>`).join(''):'<p class="empty">No screening tasks or interviews recorded yet.</p>';
}
function inCohort(r,cohort){if(!r.submittedAt)return false;if(cohort==='all')return true;const date=new Date(todayKey()+'T12:00:00Z');date.setUTCDate(date.getUTCDate()-Number(cohort)+1);return r.submittedDay>=date.toISOString().slice(0,10)&&r.submittedDay<=todayKey()}
function cohortRows(){return state.data.applications.filter(r=>inCohort(r,state.cohort))}
function reachedInterview(r){return stageOf(r)==='interview'||(r.history||[]).some(e=>e.status==='interview')}
function outcomeStats(rows){return {total:rows.length,rejected:rows.filter(r=>r.status==='rejected').length,interviews:rows.filter(reachedInterview).length,pending:rows.filter(r=>!['rejected','offer','withdrawn'].includes(r.status)).length,offers:rows.filter(r=>r.status==='offer').length}}
function renderLearning(){
 const rows=cohortRows(),totals=outcomeStats(rows),categories=[...new Set(state.data.applications.map(r=>r.category))].sort();
 $('#learning-summary').innerHTML=`<div><strong>${totals.total}</strong> submitted</div><div><strong>${totals.pending}</strong> still open</div><div><strong>${totals.rejected}</strong> rejected</div><div><strong>${totals.interviews}</strong> reached interview</div>`;
 $('#outcome-table').innerHTML=`<table class="outcome-table"><thead><tr><th>Discipline</th><th>Submitted</th><th>Still open</th><th>Rejected</th><th>Interview reach</th><th>Observed rejection share</th></tr></thead><tbody>${categories.map(c=>{const v=outcomeStats(rows.filter(r=>r.category===c));return `<tr><td><button data-learn-category="${esc(c)}">${esc(c)} ↗</button></td><td>${v.total}</td><td>${v.pending}</td><td><button data-rejected-category="${esc(c)}">${v.rejected}</button></td><td>${v.interviews}</td><td><div class="rate"><span style="width:${v.total?v.rejected/v.total*100:0}%"></span></div><small>${v.rejected} / ${v.total} · ${v.total?(v.rejected/v.total*100).toFixed(1)+'%':'—'}</small></td></tr>`}).join('')}</tbody></table>`;
 $('#analysis-note').textContent=`${totals.rejected} rejection${totals.rejected===1?'':'s'} across ${totals.total} submissions in this cohort. ${totals.pending} remain open. These are observed outcomes, not evidence that one discipline or resume performs better.`;
 $('#learn-category').innerHTML=categories.map(c=>`<option>${esc(c)}</option>`).join('');if(!categories.includes(state.learnCategory))state.learnCategory=categories.find(c=>c.includes('Robotics'))||categories[0];$('#learn-category').value=state.learnCategory;renderPlan();
 const rejected=rows.filter(r=>r.status==='rejected'),counts={};rejected.forEach(r=>{const k=r.progress?.feedback||'unspecified';counts[k]=(counts[k]||0)+1});
 $('#feedback-summary').innerHTML=Object.entries(counts).map(([k,n])=>`<div class="feedback-line"><span>${esc(feedbackNames[k])}</span><strong>${n}</strong></div>`).join('')||'<p>No rejection feedback in this cohort.</p>';
 $('#feedback-summary').innerHTML+='<p class="evidence-note"><strong>What remains unknown</strong><br>ATS filtering, missing keywords, the exact screening round, timing, and skill gaps are not established by generic rejection emails.</p>';
}
const improvementPlans={
 'Robotics & Physical AI':{hypothesis:'Role-specific evidence may be less visible for manipulation and production-control roles than for navigation and locomotion.',keywords:[['PPO · curriculum learning','Supported','Lead with GACL and the learning problem it solves.'],['Sim-to-real · reward shaping','Supported','Use RTW with the physical trial scope and your contribution.'],['Dexterous grasping · manipulation','Evidence to strengthen','Build and evaluate a manipulation task before claiming direct expertise.'],['C++ · ROS 2 · ONNX','Supported with scope','Describe the controller extension as a simulation prototype.']],resume:'Move the most relevant robot, task, algorithm and evaluation into the first two bullets. Distinguish physical-robot results from simulation-only humanoid work.',skill:'Create a reproducible manipulation benchmark with a baseline, held-out objects, failure taxonomy and a short demonstration. Start in simulation; label hardware validation only when completed.',measure:'Compare interview reach for similarly scoped early-career robotics roles. Keep manipulation and locomotion roles separate in private review notes.'},
 'RL & Language Models':{hypothesis:'Published robotics RL is transferable, but employers may need clearer evidence of LLM post-training and evaluation ownership.',keywords:[['Reinforcement learning · reward design','Supported','Anchor in GACL / RTW and identify the task domain.'],['GRPO · verifiers','Prototype evidence','Describe the small-model implementation and evaluation controls.'],['Post-training evaluation · ablations','Evidence to strengthen','Publish a held-out evaluation with seed controls and leakage checks.'],['Distributed training · CUDA','Do not add without proof','Demonstrate a measured implementation before listing these skills.']],resume:'Translate the learning problem into the employer’s terms while naming the actual model scale, environment and comparator. Do not present robotics gains as LLM benchmark improvements.',skill:'Complete one compact post-training experiment with a frozen test set, multiple seeds, a reward ablation and a clear negative-results section.',measure:'Track model-domain match, required scale and resume version before comparing later interview invitations.'},
 'Research & Applied AI':{hypothesis:'The research record may benefit from a more direct connection to the employer’s evaluation problem and expected engineering deliverable.',keywords:[['Experimental design · statistical testing','Supported','Connect AWS performance analysis to careful measurement.'],['Python · PyTorch','Supported','Name what you implemented, not only the frameworks used.'],['LLM benchmarks · error analysis','Evidence to strengthen','Show a reproducible evaluation harness with a failure taxonomy.'],['First-author research','Supported','Name authorship and the specific contribution; keep claims scoped.']],resume:'Open with the employer’s research problem, then your strongest matching contribution and measured result. Put an accessible artifact next to a publication.',skill:'Package an evaluation harness with pinned dependencies, a documented dataset split, baseline results, uncertainty and representative errors.',measure:'Compare applications requiring similar domain knowledge and seniority. A generic “closer match” email is not proof of a technical deficiency.'},
 'Machine Learning':{hypothesis:'Research models and prototypes may not fully demonstrate the production lifecycle expected by some ML engineering roles.',keywords:[['Python · PyTorch','Supported','Use implemented models and experiments.'],['Evaluation · reproducibility','Supported','Describe checks, baselines and controlled comparisons.'],['Inference optimization','Supported with scope','Report allocated memory separately from total device memory.'],['Serving · monitoring · production ownership','Evidence to strengthen','Build and measure a small end-to-end service before claiming ownership.']],resume:'Pair one modeling result with one systems result. State prototype and internship scope clearly; emphasize measurement over a long tools list.',skill:'Deploy a small demonstrator with repeatable load tests, latency/quality measurements and monitoring. Document the limits of the deployment.',measure:'Separate research-heavy ML openings from roles requiring years of production service ownership.'},
 'Software & Infrastructure':{hypothesis:'A research-heavy first page may underemphasize backend engineering and performance work for systems roles.',keywords:[['Python · C/C++','Supported','Select the relevant AWS or controller implementation.'],['Benchmarking · observability','Supported','Describe CloudWatch and statistical performance tooling.'],['Data pipelines · reliability','Evidence to strengthen','Demonstrate validation, failure handling and repeatable tests.'],['Distributed systems at scale','Do not overstate','Separate internship contributions from owning a production platform.']],resume:'Lead with the engineering bottleneck, implementation and validation. Use research only where it supports the target role’s responsibilities.',skill:'Publish a focused systems benchmark with fault cases, reproducible workloads and an explanation of tradeoffs.',measure:'Compare roles with similar language, infrastructure and experience requirements; record the resume version used.'}
};
function planMarkup(category){const p=improvementPlans[category];if(!p)return '';return `<div class="hypothesis"><span class="tag-hypothesis">Hypothesis to test</span><p>${esc(p.hypothesis)}</p></div><h4>Keyword → evidence map</h4><div class="keyword-map">${p.keywords.map(([k,s,a])=>`<div><strong>${esc(k)}</strong><span>${esc(s)}</span><p>${esc(a)}</p></div>`).join('')}</div><ol class="iteration-steps"><li><strong>Resume edit to test</strong><p>${esc(p.resume)}</p></li><li><strong>Build stronger evidence</strong><p>${esc(p.skill)}</p></li><li><strong>Measure the next cohort</strong><p>${esc(p.measure)}</p></li></ol><p class="evidence-note">Proposed work, not completed work. Use employer terminology only where a project, publication or employment contribution supports it.</p>`}
function renderPlan(){$('#improvement-plan').innerHTML=planMarkup(state.learnCategory)}
function detailInsights(r){const p=r.progress||{},rejected=stageOf(r)==='rejected';return `<section class="detail-progress"><h3>Current milestone</h3><p>${esc(roundLabel(r)||stageNames[stageOf(r)])}</p><strong>${esc(actionNames[p.nextAction]||'Review application status')}</strong>${p.nextAt?`<p>${fmt(p.nextAt,{weekday:'long',month:'long',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})} ET</p>`:''}</section>${rejected?`<section class="rejection-detail"><h3>Employer feedback</h3><p>${esc(feedbackNames[p.feedback]||feedbackNames.unspecified)}</p><p>Decision received: ${p.decisionAt?fmt(p.decisionAt):'Not recorded'}</p><p>Rejection round: ${p.rejectionStage==='before_interview'?'Before interview':p.rejectionStage==='after_interview'?'After interview':'Not stated by employer'}</p><p class="evidence-note">No recorded interview is not proof of an automated or initial-screen rejection. Review the private email for exact wording.</p></section>`:''}<details class="detail-learning"><summary>Role-family resume & skills review</summary>${planMarkup(r.category)}</details>`}
$('#stage-filter').addEventListener('change',e=>{state.stage=e.target.value;change()});
$('#cohort').addEventListener('change',e=>{state.cohort=e.target.value;renderLearning()});
$('#learn-category').addEventListener('change',e=>{state.learnCategory=e.target.value;renderPlan()});
$('#all-attention').addEventListener('click',()=>{focusStage('');state.quick='attention';change()});
document.addEventListener('click',e=>{let b=e.target.closest('[data-stage]');if(b)focusStage(b.dataset.stage);b=e.target.closest('[data-learn-category]');if(b){state.learnCategory=b.dataset.learnCategory;$('#learn-category').value=state.learnCategory;renderPlan()}b=e.target.closest('[data-rejected-category]');if(b)focusStage('rejected',b.dataset.rejectedCategory,state.cohort)});
